### ISSUE TITLE
NoneType' object has no attribute 'has'

### ISSUE THREAD

**Issue by emmtte** [Nekmo/telegram-upload#105]
* telegram-upload version: 0.4.0
* Python version: 3.7
* Operating System: piOS (raspbian)
* Dependencies list (run `pip freeze`):
````
asn1crypto==0.24.0
certifi==2018.8.24
cffi==1.14.5
chardet==3.0.4
click==7.1.2
cryptg==0.2.post0
cryptography==2.6.1
entrypoints==0.3
greenlet==1.0.0
hachoir==3.1.2
idna==2.6
keyring==17.1.1
keyrings.alt==3.1.1
msgpack==1.0.2
psutil==5.8.0
pyaes==1.6.1
pyasn1==0.4.8
pycparser==2.20
pycrypto==2.6.1
PyGObject==3.30.4
pynvim==0.4.2
python-apt==1.8.4.3
pyxattr==0.6.1
pyxdg==0.25
requests==2.21.0
rsa==4.7.2
SecretStorage==2.3.1
six==1.12.0
ssh-import-id==5.7
telegram-upload==0.4.0
Telethon==1.21.1
urllib3==1.24.1
````

### Description

Error when uploading

### What I Did
```
telegram-upload 01.mp4 --caption 01.mp4
Traceback (most recent call last):
  File "/usr/local/bin/telegram-upload", line 10, in <module>
    sys.exit(upload_cli())
  File "/usr/local/lib/python3.7/dist-packages/telegram_upload/exceptions.py", line 54, in wrap
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telegram_upload/management.py", line 111, in upload
    client.send_files(to, files, delete_on_success, print_file_id, forward)
  File "/usr/local/lib/python3.7/dist-packages/telegram_upload/client.py", line 167, in send_files
    thumb = file.get_thumbnail()
  File "/usr/local/lib/python3.7/dist-packages/telegram_upload/files.py", line 165, in get_thumbnail
    thumb = get_file_thumb(self.path)
  File "/usr/local/lib/python3.7/dist-packages/telegram_upload/files.py", line 65, in get_file_thumb
    return get_video_thumb(file)
  File "/usr/local/lib/python3.7/dist-packages/telegram_upload/video.py", line 49, in get_video_thumb
    duration = metadata.get('duration').seconds if metadata.has('duration') else 0
AttributeError: 'NoneType' object has no attribute 'has'
```

**Comment by Nekmo** [comment]
Hi @emmtte this issue is duplicated by #82 . Check the comments on that incident.

Thanks!
