### ISSUE TITLE
RPCError 400: INPUT_GZIP_INVALID

### ISSUE THREAD

**Issue by ElektroStudios** [Nekmo/telegram-upload#108]
* telegram-upload version: 0.4.0
* Python version: 3.9.2 x64
* Operating System: Microsoft Windows 10.0.18363.959
* Dependencies list (run `pip freeze`):
```
cffi==1.14.5
click==7.1.2
cryptg==0.2.post2
hachoir==3.1.2
pyaes==1.6.1
pyasn1==0.4.8
pycparser==2.20
rsa==4.7.2
telegram-upload==0.4.0
Telethon==1.21
```

### Description

When sending a file, during the upload operation about at the 95% completion, I got an exception with message text related to '**RPCError 400: INPUT_GZIP_INVALID**' :

```
Traceback (most recent call last):
  File "C:\Users\Administrador\source\repos\TelegramBackupBot\TelegramBackupBot\bin\Debug\Libs\telegram-upload-script.py", line 33, in <module>
    sys.exit(load_entry_point('telegram-upload==0.4.0', 'console_scripts', 'telegram-upload')())
  File "c:\program files\python\lib\site-packages\telegram_upload\exceptions.py", line 54, in wrap
    return fn(*args, **kwargs)
  File "c:\program files\python\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\program files\python\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python\lib\site-packages\telegram_upload\management.py", line 111, in upload
    client.send_files(to, files, delete_on_success, print_file_id, forward)
  File "c:\program files\python\lib\site-packages\telegram_upload\client.py", line 173, in send_files
    message = self._send_file_message(entity, file, thumb, progress)
  File "c:\program files\python\lib\site-packages\telegram_upload\client.py", line 123, in _send_file_message
    message = self.send_file(entity, file, thumb=thumb,
  File "c:\program files\python\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "c:\program files\python\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\program files\python\lib\site-packages\telethon\client\uploads.py", line 375, in send_file
    file_handle, media, image = await self._file_to_media(
  File "c:\program files\python\lib\site-packages\telethon\client\uploads.py", line 692, in _file_to_media
    file_handle = await self.upload_file(
  File "c:\program files\python\lib\site-packages\telethon\client\uploads.py", line 628, in upload_file
    result = await self(request)
  File "c:\program files\python\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "c:\program files\python\lib\site-packages\telethon\client\users.py", line 79, in _call
    result = await future
telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: INPUT_GZIP_INVALID (caused by SaveBigFilePartRequest)
```
![](https://i.imgur.com/lEAcPzU.png)

### What I Did

I did nothing strange, just a programmatic, automated call to run the program passing to it the corresponding command-line parameters to upload a file:

`telegram-upload.exe --force-file --caption "" --to "{telegramInviteLink}" "{file.FullName}"`

Also I must tell the file was finally uploaded correctly. As shown in the image above it was a RAR file, I was able to download the file from the Telegram's channel on which I uploaded it using telegram-upload, and I extracted the file and checked the CRC32 checksum, everything is fine, but the program maybe should have not get into that exception.

**Comment by Nekmo** [comment]
It must be probably a connection error with the servers. Even if you have a good connection, the servers may have connection failures.

I'm afraid there is no information about that error:

https://www.google.com/search?q=%22INPUT_GZIP_INVALID%22
