### ISSUE TITLE
RPCError 406: UPDATE_APP_TO_LOGIN

### ISSUE THREAD

**Issue by emmtte** [Nekmo/telegram-upload#139]
Have this error with a fresh installation
seems related with this issue : https://github.com/LonamiWebs/Telethon/issues/3215

````
Please enter your phone: ***************
Traceback (most recent call last):
  File "/usr/local/bin/telegram-download", line 10, in <module>
    sys.exit(download_cli())
  File "/usr/local/lib/python3.7/dist-packages/telegram_upload/exceptions.py", line 50, in wrap
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telegram_upload/management.py", line 120, in download
    client.start()
  File "/usr/local/lib/python3.7/dist-packages/telegram_upload/client.py", line 105, in start
    first_name=first_name, last_name=last_name, max_attempts=max_attempts)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/auth.py", line 133, in start
    else self.loop.run_until_complete(coro)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/auth.py", line 189, in _start
    await self.send_code_request(phone, force_sms=force_sms)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/auth.py", line 515, in send_code_request
    phone, self.api_id, self.api_hash, types.CodeSettings()))
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcbaseerrors.AuthKeyError: RPCError 406: UPDATE_APP_TO_LOGIN (caused by SendCodeRequest)
````

**Comment by tissole** [comment]
Update Telethon.

**Comment by Nekmo** [comment]
Closed due to inactivity.
