### ISSUE TITLE
[Solved] Can't upload any file using my invitation link

### ISSUE THREAD

**Issue by gustavolinux** [Nekmo/telegram-upload#143]
* telegram-upload version: I don't know how to check the version...
* Python version: I have these python packages below:
```
python             python2.7          python3.6          python3.7
python-config      python2.7-config   python3.6-config   python3.7m
python2            python3            python3.6m         python3m
python2-config     python3-config     python3.6m-config  python3m-config
```

* Operating System: armbian(updated)
* Dependencies list (run `pip freeze`):
```
pip freeze
asn1crypto==0.24.0                                                                       
attrs==17.4.0                                                                            
Automat==0.6.0                                                                           
backports-abc==0.5                                                                       
cachetools==2.0.0                                                                        
certifi==2018.1.18                                                                       
chardet==3.0.4                                                                           
click==7.1.2                                                                             
configobj==5.0.6                                                                         
constantly==15.1.0                                                                       
cryptography==2.1.4                                                                      
deluge==1.3.15                                                                           
Django==1.8                                                                              
django-uwsgi==0.2.1                                                                      
enum34==1.1.6                                                                            
hyperlink==17.3.1                                                                        
idna==2.6                                                                                
incremental==16.10.1                                                                     
ipaddress==1.0.17                                                                        
Mako==1.0.7                                                                              
MarkupSafe==1.0                                                                          
Mopidy==2.1.0                                                                            
Mopidy-ALSAMixer==1.0.3                                                                  
Mopidy-Beets==3.0.0                                                                      
Mopidy-Dirble==1.3.0                                                                     
Mopidy-dLeyna==1.2.0                                                                     
Mopidy-InternetArchive==2.0.0                                                            
Mopidy-Iris==3.40.0                                                                      
Mopidy-Local-Images==1.0.0
Mopidy-Local-SQLite==1.0.0
Mopidy-Moped==0.7.1
Mopidy-MPRIS==1.3.1
Mopidy-Podcast==2.0.1
Mopidy-Podcast-iTunes==2.0.0
Mopidy-Scrobbler==1.1.1
Mopidy-SomaFM==1.0.1
Mopidy-SoundCloud==2.0.2
Mopidy-TuneIn==0.4.1
Mopidy-Youtube==2.0.0
mysqlclient==1.3.10
pyalsaaudio==0.7
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycairo==1.16.2
pygobject==3.26.1
Pykka==1.2.1
pylast==2.1.0
PyMySQL==0.8.0
pyOpenSSL==17.5.0
pyrsistent==0.16.1
pysqlite==1.0.1
python-libtorrent==1.1.5
pytz==2018.3
pyxdg==0.25
requests==2.18.4
service-identity==16.0.0
singledispatch==3.4.0.3
six==1.16.0
subprocess32==3.2.7
tornado==4.5.3
Twisted==17.9.0
uritools==1.0.2
urllib3==1.22
virtualenv==16.7.9
zope.interface==4.3.2
```

**Comment by gustavolinux** [comment]
```
telegram-upload --to {https://t.me/blablabla} banda\ de\ pifanos\ de\ caruaru\ -\ 1976\ -\ banda\ de\ pifanos\ de\ caruaru\ \(forro\ em\ vinil\).rar 

Traceback (most recent call last):
  File "/usr/local/bin/telegram-upload", line 11, in <module>
    sys.exit(upload_cli())
  File "/usr/local/lib/python3.6/dist-packages/telegram_upload/exceptions.py", line 46, in wrap
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram_upload/management.py", line 45, in upload
    client.send_files(to, files, delete_on_success, print_file_id, force_file, forward, caption, no_thumbnail)
  File "/usr/local/lib/python3.6/dist-packages/telegram_upload/client.py", line 84, in send_files
    progress_callback=progress, attributes=attributes)
  File "/usr/local/lib/python3.6/dist-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/uploads.py", line 359, in send_file
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/users.py", line 430, in get_input_entity
    await self._get_entity_from_string(peer))
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/users.py", line 568, in _get_entity_from_string
    'Cannot find any entity corresponding to "{}"'.format(string)

```

**Comment by doublep21** [comment]
just use the name without the @ , so "blablabla"

**Comment by gustavolinux** [comment]
> just use the name without the @ , so "blablabla"

but it's a channel invite link, not a contact

**Comment by doublep21** [comment]
> > just use the name without the @ , so "blablabla"
> 
> but it's a channel invite link, not a contact
i think it  there is a bug for the private link , for now just make the channel public and use the name

**Comment by gustavolinux** [comment]
> > > just use the name without the @ , so "blablabla"
> > 
> > 
> > but it's a channel invite link, not a contact
> > i think there is a bug for the private link , for now just make the channel public and use the name

Thanks that worked after setting the channel to public
