### ISSUE TITLE
Error while uploading files 

### ISSUE THREAD

**Issue by PunchEnergyFTW** [Nekmo/telegram-upload#151]
* telegram-upload version: Newest (downloaded & installed today)
* Python version: pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
* Operating System: Ubuntu 20.04
* Dependencies list (run `pip freeze`):blinker==1.4
Brotli==1.0.9
certifi==2019.11.28
cffi==1.15.0
chardet==3.0.4
click==8.1.1
cryptg==0.2.post4
cryptography==2.8
cupshelpers==1.0
dbus-python==1.2.16
defer==1.0.6
distro==1.4.0
entrypoints==0.3
hachoir==3.1.2
httplib2==0.14.0
idna==2.8
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
macaroonbakery==1.3.1
mutagen==1.44.0
oauthlib==3.1.0
prompt-toolkit==3.0.28
protobuf==3.6.1
pyaes==1.6.1
pyasn1==0.4.8
pycairo==1.16.2
pycparser==2.21
pycryptodomex==3.6.1
pycups==1.9.73
PyGObject==3.36.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyRFC3339==1.1
python-apt==2.0.0+ubuntu0.20.4.7
pytz==2019.3
pyxattr==0.6.1
requests==2.22.0
requests-unixsocket==0.2.0
rsa==4.8
SecretStorage==2.3.1
simplejson==3.16.0
six==1.14.0
ssh-import-id==5.10
supervisor==4.1.0
systemd-python==234
telegram-upload==0.5.0
Telethon==1.24.0
urllib3==1.25.8
wadllib==1.3.3
wcwidth==0.2.5
websockets==8.1
youtube-dl==2020.3.24
yt-dlp==2022.3.8.2

### Description

Describe what you were trying to get done.
Uploading a bunch of videos to my Telegram Account (Saved Messages)

Tell us what happened, what went wrong, and what you expected to happen.
It works sometimes and sometimes it doesn't. When it doesnt work it has two error messages that pop up (only 1 at a time though)
I expected that the videos will get uploaded without any error-message.

### What I Did
Update the whole system (sudo apt update && sudo apt upgrade) and reinstall Telegram-Upload. The Problem still persists. Even on my second machine. It seems that some files are causing this specific error. Telegram-Upload works in Alphabetical order. When i try to upload the first file (according to the Alphabetical order) in the folder it spits out the traceback error. When i try the second video, it works just fine. Weird.
```
Paste the command(s) you ran and the output.
command: telegram-upload 1/* --delete-on-success

output(s)
First Error Message: 

Traceback (most recent call last):
  File "/usr/local/bin/telegram-upload", line 8, in <module>
    sys.exit(upload_cli())
  File "/usr/local/lib/python3.8/dist-packages/telegram_upload/exceptions.py", line 64, in wrap
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/telegram_upload/management.py", line 167, in upload
    client.send_files(to, files, delete_on_success, print_file_id, forward)
  File "/usr/local/lib/python3.8/dist-packages/telegram_upload/client.py", line 177, in send_files
    thumb = file.get_thumbnail()
  File "/usr/local/lib/python3.8/dist-packages/telegram_upload/files.py", line 165, in get_thumbnail
    thumb = get_file_thumb(self.path)
  File "/usr/local/lib/python3.8/dist-packages/telegram_upload/files.py", line 65, in get_file_thumb
    return get_video_thumb(file)
  File "/usr/local/lib/python3.8/dist-packages/telegram_upload/video.py", line 52, in get_video_thumb
    ratio = get_video_size(file)
  File "/usr/local/lib/python3.8/dist-packages/telegram_upload/video.py", line 38, in get_video_size
    video_lines = re.findall(': Video: ([^\n]+)', stderr.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 2662: invalid continuation byte


Second Error Message: 
Telegram is having internal issues RpcCallFailError: Telegram is having internal issues, please try again later. (caused by SendMediaRequest)

If there was a crash, please include the traceback here.
-> see above
```

**Comment by Nekmo** [comment]
Fixed. Thanks!
