### ISSUE TITLE
.FLV files

### ISSUE THREAD

**Issue by 1581-netizen** [Nekmo/telegram-upload#176]
* telegram-upload version: 0.5.1
* Python version: Python 3.10.4
* Operating System: Ubuntu 22.04
* Dependencies list (run `pip freeze`):
```
certifi==2022.9.14
charset-normalizer==2.1.1
click==8.1.3
cryptg==0.3.1
cv2-tools==2.4.0
DateTime==4.7
decorator==4.4.2
dnspython==2.2.1
ffmpeg==1.4
ffmpeg-python==0.2.0
future==0.18.2
hachoir==3.1.3
idna==3.4
ImageHash==4.3.0
imageio==2.21.3
imageio-ffmpeg==0.4.7
mongo==0.2.0
moviepy==1.0.3
numpy==1.23.3
opencv-contrib-python==4.5.5.64
opencv-python==4.5.5.64
opencv-python-headless==4.5.5.64
Pillow==9.2.0
proglog==0.1.10
prompt-toolkit==3.0.31
pyaes==1.6.1
pyasn1==0.4.8
pylibscrypt==2.0.0
pymongo==4.2.0
python-constraint==1.4.0
python-magic==0.4.27
pytz==2022.2.1
PyWavelets==1.4.1
requests==2.28.1
rsa==4.9
scipy==1.9.1
scrypt==0.8.20
subprocess.run==0.0.8
telegram-upload==0.5.1
Telethon==1.25.0
tqdm==4.64.1
urllib3==1.26.12
ushlex==0.99.1
voluptuous==0.13.1
wcwidth==0.2.5
zope.interface==5.4.0
```

### Description

When I try to send .FLV files, they are not sent and I get the error below

### What I Did

```
telegram-upload /mnt/todo/sample_640x360.flv
Traceback (most recent call last):
  File "/docker/pycharm/bin/telegram-upload", line 8, in <module>
    sys.exit(upload_cli())
  File "/docker/pycharm/lib/python3.10/site-packages/telegram_upload/exceptions.py", line 64, in wrap
    return fn(*args, **kwargs)
  File "/docker/pycharm/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/docker/pycharm/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/docker/pycharm/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/docker/pycharm/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/docker/pycharm/lib/python3.10/site-packages/telegram_upload/management.py", line 172, in upload
    client.send_files(to, files, delete_on_success, print_file_id, forward)
  File "/docker/pycharm/lib/python3.10/site-packages/telegram_upload/client.py", line 183, in send_files
    message = self._send_file_message(entity, file, thumb, progress)
  File "/docker/pycharm/lib/python3.10/site-packages/telegram_upload/client.py", line 136, in _send_file_message
    progress_callback=progress, attributes=file.file_attributes)
  File "/docker/pycharm/lib/python3.10/site-packages/telegram_upload/files.py", line 181, in file_attributes
    return get_file_attributes(self.path)
  File "/docker/pycharm/lib/python3.10/site-packages/telegram_upload/files.py", line 54, in get_file_attributes
    (0, metadata.get('duration').seconds)[metadata.has('duration')],
  File "/docker/pycharm/lib/python3.10/site-packages/hachoir/metadata/metadata.py", line 81, in get
    raise ValueError(
ValueError: Metadata has no value 'duration' (index 0)

```

**Comment by Nekmo** [comment]
Fixed in version v0.7.0.
