### ISSUE TITLE
Error On ARM (Raspberry Pi)

### ISSUE THREAD

**Issue by a-y-a-n-das** [Nekmo/telegram-upload#188]
* telegram-upload version: 0.5.1
* Python version: 3.9.2
* Operating System: Rasberry Pi OS Lite
* Dependencies list (run `pip freeze`): certifi==2020.6.20
chardet==4.0.0
click==8.1.3
colorzero==1.1
cryptg==0.4.0
distro==1.5.0
gpiozero==1.6.2
hachoir==3.2.0
idna==2.10
numpy==1.19.5
picamera2==0.3.9
pidng==4.0.9
piexif==1.1.3
Pillow==8.1.2
prompt-toolkit==3.0.38
pyaes==1.6.1
pyasn1==0.5.0
python-apt==2.2.1
python-prctl==1.7
requests==2.25.1
RPi.GPIO==0.7.0
rsa==4.9
scandir==1.10.0
simplejpeg==1.6.4
six==1.16.0
spidev==3.5
ssh-import-id==5.10
telegram-upload==0.5.1
Telethon==1.28.5
toml==0.10.1
urllib3==1.26.5
v4l2-python3==0.3.2
wcwidth==0.2.6

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did
I am trying to upload a file to a group chat with chat id.
but end up getting a time out error and "ValueError: Cannot find any entity corresponding to "-1001973708029"
"  But without chat id its working fine uploading  files to saved files in telegram account.

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.

telegram-upload --to <chat id> sf.zip

Traceback (most recent call last):
  File "/usr/local/bin/telegram-upload", line 8, in <module>
    sys.exit(upload_cli())
  File "/usr/local/lib/python3.9/dist-packages/telegram_upload/exceptions.py", line 64, in wrap
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram_upload/management.py", line 172, in upload
    client.send_files(to, files, delete_on_success, print_file_id, forward)
  File "/usr/local/lib/python3.9/dist-packages/telegram_upload/client.py", line 183, in send_files
    message = self._send_file_message(entity, file, thumb, progress)
  File "/usr/local/lib/python3.9/dist-packages/telegram_upload/client.py", line 133, in _send_file_message
    message = self.send_file(entity, file, thumb=thumb,
  File "/usr/local/lib/python3.9/dist-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/uploads.py", line 356, in send_file
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 432, in get_input_entity
    await self._get_entity_from_string(peer))
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 569, in _get_entity_from_string
    raise ValueError(
ValueError: Cannot find any entity corresponding to "-1001973708029"


```

**Comment by Nekmo** [comment]
Entity by id is not supported in version v0.5.0. Version v0.6.0 supports this feature. The new version will be available shortly. Thank you.
