### ISSUE TITLE
Windows support for videos

### ISSUE THREAD

**Issue by finnyfound** [Nekmo/telegram-upload#21]
* telegram-upload version: 0.1.10
* Python version: 3.7.3
* Operating System:Windows 10 Pro

### Description

Error Occured
```
Traceback (most recent call last):
  File "telegram-upload", line 6, in <module>
    catch(manage)()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram_upload\exceptions.py", line 25, in wrap
    fn(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram_upload\management.py", line 18, in manage
    client.send_files(to, files, delete_on_success)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram_upload\client.py", line 44, in send_files
    length=os.path.getsize(file))
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'H:\\Music\\Den\\The_Den_-_Trojans\\01
```

### What I Did

```
Tried to upload a file or from folders with space character

the command i ran 
`python telegram-upload H:\Music\Den\The_Den_-_Trojans\01 Tr+jans.mp3`
```

**Comment by Nekmo** [comment]
Test using quotes.

**Comment by finnyfound** [comment]
Thanks it worked, would you mind updating the ReadMe file for future users?

**Comment by finnyfound** [comment]
Uploaded 1 file successfully then this error occurred.

command used
`python telegram-upload "H:\Music\Den\The_Den_-_Trojans\01 Tr+jans.mp3"`

```
Traceback (most recent call last):
  File "telegram-upload", line 6, in <module>
    catch(manage)()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram_upload\exceptions.py", line 25, in wrap
    fn(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram_upload\management.py", line 18, in manage
    client.send_files(to, files, delete_on_success)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram_upload\client.py", line 51, in send_files
    thumb = get_file_thumb(file)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram_upload\files.py", line 36, in get_file_thumb
    return get_video_thumb(file)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram_upload\video.py", line 38, in get_video_thumb
    ], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by Nekmo** [comment]
I would have to disable support for videos in Windows. This is a problem of support for Windows.

**Comment by Nekmo** [comment]
Now telegram-upload uses `ffmpeg.exe` for Windows and `FFMPEG_COMMAND` environment variable is now available.
