### ISSUE TITLE
--caption is broken with python 3.12

### ISSUE THREAD

**Issue by narutojawad** [Nekmo/telegram-upload#249]
* telegram-upload version:0.7.1
* Python version:3.12
* Operating System: Windows 10

### Description

the tool works fine but when "--caption" is used it Crashes.

### What I Did

```
Any command with (--caption) in it will crash.
telegram-upload --caption {file.name} --to "********" --force-file "File.ext "File2.ext"
```
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\sd\AppData\Roaming\Python\Python312\Scripts\telegram-upload.exe\__main__.py", line 7, in <module>
  File "C:\Users\sd\AppData\Roaming\Python\Python312\site-packages\telegram_upload\exceptions.py", line 68, in wrap
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sd\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sd\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\sd\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sd\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sd\AppData\Roaming\Python\Python312\site-packages\telegram_upload\management.py", line 191, in upload
    client.send_files(to, files, delete_on_success, print_file_id, forward)
  File "C:\Users\sd\AppData\Roaming\Python\Python312\site-packages\telegram_upload\client\telegram_upload_client.py", line 126, in send_files
    message = self.send_one_file(entity, file, send_as_media, thumb=thumb)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sd\AppData\Roaming\Python\Python312\site-packages\telegram_upload\client\telegram_upload_client.py", line 103, in send_one_file
    message = self._send_file_message(entity, file, thumb, progress)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sd\AppData\Roaming\Python\Python312\site-packages\telegram_upload\client\telegram_upload_client.py", line 58, in _send_file_message
    caption=file.file_caption, force_document=file.force_file,
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\sd\AppData\Roaming\Python\Python312\site-packages\telegram_upload\upload_files.py", line 177, in file_caption
    caption = formatter.format(self._caption, file=FilePath(self.path), now=datetime.datetime.now())
                                                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sd\AppData\Roaming\Python\Python312\site-packages\telegram_upload\caption_formatter.py", line 303, in __new__
    self = cls._from_parts(args)
           ^^^^^^^^^^^^^^^
AttributeError: type object 'WindowsFilePath' has no attribute '_from_parts'. Did you mean: '_load_parts'?`

**Comment by pokedo0** [comment]
![Image](https://github.com/user-attachments/assets/5b2943d8-02b8-4650-b260-b17d136de8d9)

work for me now, code from chatgpt

**Comment by ElektroStudios** [comment]
The code above in plain text:

```python
class FilePath(FileMixin, Path):
    def __new__(cls, *args, **kwargs):
        if cls is FilePath:
            cls = WindowsFilePath if os.name == 'nt' else PosixFilePath
        
        path = Path(*args)
        self = cls(*path.parts)
        #if not self._flavour.is_supported:
        #    raise NotImplementedError("cannot instantiate %r on your system"
        #                              % (cls.__name__,))
        return self
```
The file to be edited with that updated code is located at: 
`C:\Program Files\Python\Lib\site-packages\telegram_upload\caption_formatter.py`
