### ISSUE TITLE
uploading causes repeated telethon.errors.rpcbaseerrors.FloodError: RPCError 420: FLOOD_PREMIUM_WAIT_3 (caused by SaveBigFilePartRequest)

### ISSUE THREAD

**Issue by Paladin-z** [Nekmo/telegram-upload#266]
* telegram-upload version: v0.7.1
* Python version: 3.9.2
* Operating System: Debian 11 (bullseye)
* Dependencies list (run `pip freeze`):
* app-version==1.0.1
attrs==21.4.0
Automat==22.10.0
cffi==1.15.1
chardet==4.0.0
configparser==4.0.2
constantly==15.1.0
contextlib2==0.6.0.post1
cryptography==3.3.2
distlib==0.3.6
enum34==1.1.10
filelock==3.2.1
hyperlink==21.0.0
idna==2.10
importlib-metadata==2.1.3
importlib-resources==3.3.1
incremental==22.10.0
ipaddress==1.0.23
lxml==4.9.1
Mako==1.1.6
MarkupSafe==1.1.1
notify==0.3.1
pathlib2==2.3.7.post1
platformdirs==2.0.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pygame==2.0.3
PyHamcrest==1.10.1
pyOpenSSL==21.0.0
pyxdg==0.28
scandir==1.10.0
service-identity==21.1.0
singledispatch==3.7.0
six==1.16.0
Twisted==20.3.0
typing==3.10.0.0
validate-email==1.3
virtualenv==20.15.1
zipp==1.2.0
zope.interface==5.5.0

### Description

Uploading a large file with --large-files split 

### What I Did
 telegram-upload --to [REDACTED] --large-files split somefile.mkv
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
4Task exception was never retrieved
future: <Task finished name='telegram-upload-file-287' coro=<TelegramUploadClient._send_file_part() done, defined at /usr/local/lib/python3.9/dist-packages/telegram_upload/client/telegram_upload_client.py:330> exception=FloodError('RPCError 420: FLOOD_PREMIUM_WAIT_3 (caused by SaveBigFilePartRequest)')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/telegram_upload/client/telegram_upload_client.py", line 346, in _send_file_part
    result = await self(request)
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 87, in _call
    result = await future
telethon.errors.rpcbaseerrors.FloodError: RPCError 420: FLOOD_PREMIUM_WAIT_3 (caused by SaveBigFilePartRequest)
Task exception was never retrieved
future: <Task finished name='telegram-upload-file-288' coro=<TelegramUploadClient._send_file_part() done, defined at /usr/local/lib/python3.9/dist-packages/telegram_upload/client/telegram_upload_client.py:330> exception=FloodError('RPCError 420: FLOOD_PREMIUM_WAIT_3 (caused by SaveBigFilePartRequest)')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/telegram_upload/client/telegram_upload_client.py", line 346, in _send_file_part
    result = await self(request)
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 87, in _call
    result = await future
telethon.errors.rpcbaseerrors.FloodError: RPCError 420: FLOOD_PREMIUM_WAIT_3 (caused by SaveBigFilePartRequest)
Task exception was never retrieved
future: <Task finished name='telegram-upload-file-289' coro=<TelegramUploadClient._send_file_part() done, defined at /usr/local/lib/python3.9/dist-packages/telegram_upload/client/telegram_upload_client.py:330> exception=FloodError('RPCError 420: FLOOD_PREMIUM_WAIT_3 (caused by SaveBigFilePartRequest)')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/telegram_upload/client/telegram_upload_client.py", line 346, in _send_file_part
    result = await self(request)
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 87, in _call
    result = await future
telethon.errors.rpcbaseerrors.FloodError: RPCError 420: FLOOD_PREMIUM_WAIT_3 (caused by SaveBigFilePartRequest)
Task exception was never retrieved
future: <Task finished name='telegram-upload-file-290' coro=<TelegramUploadClient._send_file_part() done, defined at /usr/local/lib/python3.9/dist-packages/telegram_upload/client/telegram_upload_client.py:330> exception=FloodError('RPCError 420: FLOOD_PREMIUM_WAIT_3 (caused by SaveBigFilePartRequest)')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/telegram_upload/client/telegram_upload_client.py", line 346, in _send_file_part
    result = await self(request)
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 87, in _call
    result = await future
telethon.errors.rpcbaseerrors.FloodError: RPCError 420: FLOOD_PREMIUM_WAIT_3 (caused by SaveBigFilePartRequest)
^C

Aborted!

**Comment by lriuui0x0** [comment]
I encountered the same error as well, this error seems can be simply ignored and retried

**Comment by tosankrisna11** [comment]
that because you try to upload more than 2gb file in non premium telegram account

**Comment by wildirisrest** [comment]
have you found any solutions?

**Comment by Paladin-z** [comment]
It seems this probably telegram heavily rate limiting free users, when I upgraded to Telegram Premium all the issues stopped.
