### ISSUE TITLE
Unable to send files to a chat_id

### ISSUE THREAD

**Issue by FXeio** [Nekmo/telegram-upload#35]
* telegram-upload version: 0.3.0
* Python version: Python 3.6.9
* Operating System: Linux ubuntu 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 18.04)

### Description

I'm trying to upload a file and send it to a specific chat_id (a channel).
Application crashed apparently while trying to find entity from the provided chat_id.

I also tried sending the same file to an user_id but it failed anyway. Using `--to Username` works but since the channel I wanna use is private, it doesn't have an username.
To find out chat ids I used t.me/userinfobot

### What I Did

```
$ telegram-upload --to -1001147180984 mongodump_2020-05-08_14\:40\:21_CEST.gz 
Traceback (most recent call last):
  File "/usr/local/bin/telegram-upload", line 11, in <module>
    sys.exit(upload_cli())
  File "/usr/local/lib/python3.6/dist-packages/telegram_upload/exceptions.py", line 42, in wrap
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram_upload/management.py", line 41, in upload
    client.send_files(to, files, delete_on_success, print_file_id, force_file, forward, caption)
  File "/usr/local/lib/python3.6/dist-packages/telegram_upload/client.py", line 77, in send_files
    progress_callback=progress, attributes=attributes)
  File "/usr/local/lib/python3.6/dist-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/uploads.py", line 331, in send_file
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/users.py", line 404, in get_input_entity
    await self._get_entity_from_string(peer))
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/users.py", line 538, in _get_entity_from_string
    'Cannot find any entity corresponding to "{}"'.format(string)
ValueError: Cannot find any entity corresponding to "-1001147180984"
```

**Comment by FXeio** [comment]
After taking a look at Telethon's source code, I found out that the `--to` parameter accepts only phone, username and invite links. Using an invite link instead of a chat_id works as expected

_Source:_ https://github.com/LonamiWebs/Telethon/blob/4393ec0b83d511b6a20d8a20334138730f084375/telethon/client/users.py#L480

**Comment by Nekmo** [comment]
This is a documentation mistake. It will be fixed in the next release. Thanks!
