### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by nikotz** [Nekmo/telegram-upload#36]
* telegram-upload version:0.2.1
* Python version:3.7
* Operating System:macos

Traceback (most recent call last):
  File "/usr/local/bin/Telegram-upload", line 6, in <module>
    catch(upload)()
  File "/usr/local/lib/python3.7/site-packages/telegram_upload/exceptions.py", line 25, in wrap
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/telegram_upload/management.py", line 17, in upload
    client = Client(config or default_config())
  File "/usr/local/lib/python3.7/site-packages/telegram_upload/client.py", line 43, in __init__
    super().__init__(config.get('session', 'telegram-upload'), config['api_id'], config['api_hash'], **kwargs)
  File "/usr/local/lib/python3.7/site-packages/telethon/client/telegrambaseclient.py", line 250, in __init__
    session = SQLiteSession(session)
  File "/usr/local/lib/python3.7/site-packages/telethon/sessions/sqlite.py", line 47, in __init__
    c.execute("select name from sqlite_master "
sqlite3.OperationalError: database is locked

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
url=XXXX
for f in "$url"*.mp4 ; do 
Telegram-upload --to webcamcol  "$f" 
done

**Comment by Nekmo** [comment]
From telethon docs:

> An older process is still running and is using the same 'session' file.
> 
> This error occurs when two or more clients use the same session, that is, when you write the same session name to be used in the client:
> 
> You have an older process using the same session file.
> You have two different scripts running (interactive sessions count too).
> You have two clients in the same script running at the same time.
> The solution is, if you need two clients, use two sessions. If the problem persists and you’re on Linux, you can use fuser my.session to find out the process locking the file. As a last resort, you can reboot your system.

https://docs.telethon.dev/en/latest/quick-references/faq.html#sqlite3-operationalerror-database-is-locked

**Comment by Nekmo** [comment]
TODO: Add this error to documentation.

**Comment by Nekmo** [comment]
Added to documentation, thanks!
