### ISSUE TITLE
How to upload files?

### ISSUE THREAD

**Issue by cyberboysumanjay** [Nekmo/telegram-upload#6]
* telegram-upload version: 0.1.5
* Python version: 3.5
* Operating System: Elementary OS

### Description

Describe what you were trying to get done.
I was trying to upload file using telegram-upload
Tell us what happened, what went wrong, and what you expected to happen.
File wasn't uploaded and I got a warning.
### What I Did
I ran the command
`telegram-upload /home/cyberboy/python/TelegramBot/test100k.db`

```
Paste the command(s) you ran and the output.
```
/usr/local/lib/python3.5/dist-packages/telegram_upload/client.py:31: RuntimeWarning: coroutine 'UploadMethods.send_file' was never awaited
  progress_callback=progress, attributes=get_file_attributes(file))
```

If there was a crash, please include the traceback here.
```

I'm not able to understand how  to make it upload a certain file. I also had a query whether it can send the uploaded file to a member having a certain chat_id ?

A documentation of how to use this will be very useful.

**Comment by Nekmo** [comment]
By default telegram-upload sends the files to your own user (me). You can specify the user (using @user or id) with the `--to` parameter.

Help:

```
(tmp-103922b346dce22) [nekmo@homura ~/.virtualenvs/tmp-103922b346dce22]$ telegram-upload --help
Usage: telegram-upload [OPTIONS] [FILES]...

Options:
  --to TEXT
  --config TEXT
  -d, --delete-on-success
  --help                   Show this message and exit.
```

**Comment by cyberboysumanjay** [comment]
When I ran the command I got this:

usr/local/lib/python3.5/dist-packages/telegram_upload/client.py:31: RuntimeWarning: coroutine 'UploadMethods.send_file' was never awaited
progress_callback=progress, attributes=get_file_attributes(file))

I check my saved messages and file wasn't sent there!

**Comment by Nekmo** [comment]
I'm going to check it. Something may have changed in the dependencies.

**Comment by cyberboysumanjay** [comment]
telegram-upload --to chat_id test.txt doesn't seem to work.
When I tried telegram-upload --to @cyberboysumanjay test.txt works. 

Traceback (most recent call last):
  File "/usr/local/bin/telegram-upload", line 6, in <module>
    catch(manage)()
  File "/usr/local/lib/python3.4/dist-packages/telegram_upload/exceptions.py", line 25, in wrap
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/telegram_upload/management.py", line 18, in manage
    client.send_files(to, files, delete_on_success)
  File "/usr/local/lib/python3.4/dist-packages/telegram_upload/client.py", line 36, in send_files
    progress_callback=progress, attributes=get_file_attributes(file))
  File "/usr/local/lib/python3.4/dist-packages/telethon/client/uploads.py", line 144, in send_file
    entity = self.get_input_entity(entity)
  File "/usr/local/lib/python3.4/dist-packages/telethon/client/users.py", line 260, in get_input_entity
    self._get_entity_from_string(peer))
  File "/usr/local/lib/python3.4/dist-packages/telethon/client/users.py", line 360, in _get_entity_from_string
    'Cannot find any entity corresponding to "{}"'.format(string)
ValueError: Cannot find any entity corresponding to "286038789"

I got this when I run --to chat_id. I rechecked my chat_id and my chat_id exists.

**Comment by Nekmo** [comment]
How did you get your chat_id?

**Comment by cyberboysumanjay** [comment]
I used python-telegram-bot for that. 
update.message.chat_id gives chat_id. I have tested it and it works.
I have also sent a message using the received chat_id using api.telegram.org

**Comment by Nekmo** [comment]
Telegram-upload uses Telethon. You can read Telethon documentation:

https://github.com/LonamiWebs/Telethon/blob/master/readthedocs/extra/basic/entities.rst

Right now I can not prove it, but according to the documentation an id should work.
