### ISSUE TITLE
App crashes on R-PI

### ISSUE THREAD

**Issue by Lavmint** [Nekmo/telegram-upload#72]
* telegram-upload version: 0.3.4
* Python version: 3.8.5
* Operating System: Linux alarmpi 5.4.68-2-ARCH #1 SMP PREEMPT Wed Sep 30 14:57:27 UTC 2020 armv7l GNU/Linux

### Description

Tried to upload file from raspberry-pi and app crashed after successfull auth

### What I Did
```
alarm@alarmpi /d/Audio> telegram-upload HORRORKING.tar
Traceback (most recent call last):
  File "/usr/bin/telegram-upload", line 8, in <module>
    sys.exit(upload_cli())
  File "/usr/lib/python3.8/site-packages/telegram_upload/exceptions.py", line 46, in wrap
    fn(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/telegram_upload/management.py", line 45, in upload
    client.send_files(to, files, delete_on_success, print_file_id, force_file, forward, caption, no_thumbnail)
  File "/usr/lib/python3.8/site-packages/telegram_upload/client.py", line 82, in send_files
    message = self.send_file(entity, file, thumb=thumb,
  File "/home/alarm/.local/lib/python3.8/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/alarm/.local/lib/python3.8/site-packages/telethon/client/uploads.py", line 327, in send_file
    file_handle, media, image = await self._file_to_media(
  File "/home/alarm/.local/lib/python3.8/site-packages/telethon/client/uploads.py", line 628, in _file_to_media
    file_handle = await self.upload_file(
  File "/home/alarm/.local/lib/python3.8/site-packages/telethon/sync.py", line 34, in syncified
    coro = method(*args, **kwargs)
TypeError: upload_file() missing 1 required keyword-only argument: 'file_size'

```

**Comment by Nekmo** [comment]
Hi @Lavmint ,

Paste the output of the pip freeze command here to debug the dependencies.

Thanks!

**Comment by Lavmint** [comment]
```
> pip freeze
aiodns==2.0.0
aiohttp==3.6.2
appdirs==1.4.4
asn1crypto==1.4.0
async-timeout==3.0.1
attrs==20.3.0
base58==1.0.3
blinker==1.4
Brotli==1.0.9
brotlipy==0.7.0
CacheControl==0.12.6
cchardet==2.1.6
cffi==1.14.3
chardet==3.0.4
click==7.1.2
colorama==0.4.3
contextlib2==0.6.0.post1
cryptg==0.2.post0
cryptography==3.1.1
distlib==0.3.1
distro==1.5.0
Flask==1.1.2
h11==0.10.0
h2==3.2.0
hachoir==3.1.1
hpack==3.0.0
html5lib==1.1
hyperframe==5.2.0
idna==2.10
isc==2.0
itsdangerous==1.1.0
Jinja2==2.11.2
kaitaistruct==0.8
ldap3==2.8.1
logaugment==0.1.3
MarkupSafe==1.1.1
mitmproxy==5.2
msgpack==1.0.0
multidict==4.7.6
ordered-set==4.0.2
packaging==20.4
passlib==1.7.2
pep517==0.8.2
ply==3.11
progress==1.5
protobuf==3.12.4
publicsuffix2==2.20191221
pyaes==1.6.1
pyasn1==0.4.8
pycares==3.1.1
pycparser==2.20
pyOpenSSL==19.1.0
pyparsing==2.4.7
pyperclip==1.7.0
pytoml==0.1.21
requests==2.24.0
resolvelib==0.4.0
retrying==1.3.3
rsa==4.6
ruamel.yaml==0.16.12
ruamel.yaml.clib==0.2.2
six==1.15.0
sortedcontainers==2.2.2
telegram-upload==0.3.4
Telethon==1.10.8
TgCrypto==1.2.0
toml==0.10.1
tornado==6.0.4
uritools==3.0.0
urlextract==0.14.0
urllib3==1.25.10
urwid==2.1.1
webencodings==0.5.1
Werkzeug==1.0.1
wsproto==0.15.0
yarl==1.6.2
zipstream-new==1.1.7
zstandard==0.14.0
```
```
> pacman -Q | grep python
python 3.8.5-2
python-appdirs 1.4.4-1
python-asn1crypto 1.4.0-1
python-blinker 1.4-7
python-brotli 1.0.9-2
python-cachecontrol 0.12.6-1
python-cffi 1.14.3-1
python-chardet 3.0.4-5
python-click 7.1.2-1
python-colorama 0.4.3-1
python-contextlib2 0.6.0.post1-1
python-cryptography 3.1.1-1
python-distlib 0.3.1-1
python-distro 1.5.0-1
python-flask 1.1.2-2
python-h11 0.10.0-1
python-h2 3.2.0-2
python-hpack 3.0.0-4
python-html5lib 1.1-1
python-hyperframe 5.2.0-4
python-idna 2.10-1
python-itsdangerous 1.1.0-4
python-jinja 2.11.2-1
python-kaitaistruct 0.8-5
python-ldap3 2.8.1-1
python-markupsafe 1.1.1-4
python-msgpack 1.0.0-1
python-ordered-set 4.0.2-1
python-packaging 20.4-1
python-passlib 1.7.2-1
python-pep517 0.8.2-1
python-pip 20.1.1-1
python-ply 3.11-5
python-progress 1.5-3
python-protobuf 3.12.4-1
python-publicsuffix2 2.20191221-2
python-pyasn1 0.4.8-2
python-pycparser 2.20-1
python-pyopenssl 19.1.0-2
python-pyparsing 2.4.7-1
python-pyperclip 1.8.0-1
python-pytoml 0.1.21-4
python-requests 2.24.0-1
python-resolvelib 0.4.0-1
python-retrying 1.3.3-7
python-ruamel-yaml 0.16.12-1
python-ruamel.yaml.clib 0.2.2-1
python-setuptools 1:50.3.0-1
python-six 1.15.0-1
python-sortedcontainers 2.2.2-1
python-toml 0.10.1-2
python-tornado 6.0.4-2
python-urllib3 1.25.10-1
python-urwid 2.1.1-1
python-webencodings 0.5.1-4
python-werkzeug 1.0.1-2
python-wsproto 0.15.0-3
python-zstandard 0.14.0-1
```

**Comment by Nekmo** [comment]
@Lavmint you have a very old version of Telethon, try updating it:

```
$ pip install -U Telethon
```

**Comment by Lavmint** [comment]
@Nekmo I did as you suggested and all works now <3
Idk why version of this package was so old I thought pip resolves package dependencies...
Anyway thanks a lot and sorry for bothering you with this issue
