### ISSUE TITLE
Crash with python errors

### ISSUE THREAD

**Issue by gustavolinux** [Nekmo/telegram-upload#73]
* telegram-upload version: it was installed from git
* Python version: 3.6
* Operating System: armbian

### Description

It was running without any issues, then started to crash with the output below:

### What I Did

```
telegram-upload backup.7z 
Traceback (most recent call last):
  File "/usr/local/bin/telegram-upload", line 11, in <module>
    sys.exit(upload_cli())
  File "/usr/local/lib/python3.6/dist-packages/telegram_upload/exceptions.py", line 46, in wrap
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram_upload/management.py", line 39, in upload
    client = Client(config or default_config())
  File "/usr/local/lib/python3.6/dist-packages/telegram_upload/client.py", line 50, in __init__
    super().__init__(config.get('session', 'telegram-upload'), config['api_id'], config['api_hash'], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/telegrambaseclient.py", line 264, in __init__
    session = SQLiteSession(session)
  File "/usr/local/lib/python3.6/dist-packages/telethon/sessions/sqlite.py", line 107, in __init__
    )"""
  File "/usr/local/lib/python3.6/dist-packages/telethon/sessions/sqlite.py", line 162, in _create_table
    c.execute('create table {}'.format(definition))
sqlite3.OperationalError: disk I/O error

```

**Comment by Nekmo** [comment]
Hi @gustavolinux ,

This doesn't look like a Telegram-upload bug. Maybe your microsd card is starting to fail, it is a frequent error in RPI. 

Check the disk of your machine.

**Comment by Kemal6706150033** [comment]
hi @Nekmo ,
how to use this in python script not from CMD? 
can u give example please thank u so much for this work 😊

**Comment by Nekmo** [comment]
Closed due to inactivity.
