### ISSUE TITLE
How to upload entire folder in Windows 10

### ISSUE THREAD

**Issue by mikan01** [Nekmo/telegram-upload#78]
* telegram-upload version: Latest
* Python version: 3.9
* Operating System: Windows 10
* Dependencies list (run `pip freeze`):

### Description

I am able to upload the individual files through telegram upload command but cannot upload the entire directory by appending * at the end of the path like in Ubuntu. Any workaround?

### What I Did

```
telegram-upload "E:\new\*"

```
Traceback (most recent call last):
  File "c:\users\fang yuan\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\fang yuan\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Fang Yuan\AppData\Local\Programs\Python\Python39\Scripts\telegram-upload.exe\__main__.py", line 7, in <module>
  File "c:\users\fang yuan\appdata\local\programs\python\python39\lib\site-packages\telegram_upload\exceptions.py", line 46, in wrap
    fn(*args, **kwargs)
  File "c:\users\fang yuan\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\fang yuan\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\fang yuan\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\fang yuan\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\fang yuan\appdata\local\programs\python\python39\lib\site-packages\telegram_upload\management.py", line 45, in upload
    client.send_files(to, files, delete_on_success, print_file_id, force_file, forward, caption, no_thumbnail)
  File "c:\users\fang yuan\appdata\local\programs\python\python39\lib\site-packages\telegram_upload\client.py", line 66, in send_files
    file_size = os.path.getsize(file)
  File "c:\users\fang yuan\appdata\local\programs\python\python39\lib\genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'E:\\new\\*'```
```

**Comment by Nekmo** [comment]
Cmd does not have wildcard support: https://superuser.com/questions/460598/is-there-any-way-to-get-the-windows-cmd-shell-to-expand-wildcard-paths

The next version of Telegram-upload has support for uploading directories. It is available in the development branch.

Issue #2

**Comment by Nekmo** [comment]
Closed due to inactivity.
