### ISSUE TITLE
Forward not working

### ISSUE THREAD

**Issue by neodada** [Nekmo/telegram-upload#88]
* telegram-upload version: 0.4.0
* Python version: 3.9.1
* Operating System: Android 10
* Dependencies list (run `pip freeze`): cffi==1.14.4
click==7.1.2
cryptg==0.2.post0
hachoir==3.1.1
Jinja2==2.11.2
MarkupSafe==1.1.1
numpy==1.19.4
parsedatetime==2.6
Pillow==8.0.1
pyaes==1.6.1
pyasn1==0.4.8
pycparser==2.20
rsa==4.6
telegram-upload==0.4.0
Telethon==1.18.2
texttable==1.6.3
vcsi==7.0.12

### Description

Always getting error "Cannot find any entity" when using -f. 

### What I Did

```
**Command**
`telegram-upload -f 1469866822 "/storage/emulated/0/did"`
**Log**
`Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/telegram-upload", line 8, in <module>
    sys.exit(upload_cli())
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telegram_upload/exceptions.py", line 50, in wrap
    return fn(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telegram_upload/management.py", line 101, in upload
    client.send_files(to, files, delete_on_success, print_file_id, force_file, forward, caption, thumbnail)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telegram_upload/client.py", line 157, in send_files
    self.forward_to(message, forward)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telegram_upload/client.py", line 188, in forward_to
    self.forward_messages(destination, [message])
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/data/data/com.termux/files/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/client/messages.py", line 894, in forward_messages
    entity = await self.get_input_entity(entity)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/client/users.py", line 432, in get_input_entity
    await self._get_entity_from_string(peer))
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/client/users.py", line 569, in _get_entity_from_string
    raise ValueError(
ValueError: Cannot find any entity corresponding to "1469866822"`
```

**Comment by Nekmo** [comment]
Hello, 

Try using a phone number, username, invite link or “me”. This is probably a misprint in the documentation.

**Comment by neodada** [comment]
> Hello,
> 
> Try using a phone number, username, invite link or “me”. This is probably a misprint in the documentation.

How to use invite link?
Should i use https://t.me/joinchat/xxxxxxxxxx
Or just xxxxxxxxxxx

Edit: 1st one worked.
