### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/app/.config/telegram-upload.json'

### ISSUE THREAD

**Issue by cyberboysumanjay** [Nekmo/telegram-upload#9]
* telegram-upload version: 0.1.6
* Python version: 3.6.6
* Operating System: Linux

### Description
When I triggered the command telegram-upload runtime.txt on my heroku server and entered my app_id and app_hash.

Instead of asking about my phone number it gave this error.

### What I Did
~ $ telegram-upload runtime.txt 
Go to https://my.telegram.org and create a App in API development tools
Please Enter api_id: XXXXX
Now enter api_hash: XXXXXXXXXXXXXXXXXXXX
Traceback (most recent call last):
  File "/app/.heroku/python/bin/telegram-upload", line 6, in <module>
    catch(manage)()
  File "/app/.heroku/python/lib/python3.6/site-packages/telegram_upload/exceptions.py", line 25, in wrap
    fn(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/app/.heroku/python/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/.heroku/python/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/telegram_upload/management.py", line 16, in manage
    client = Client(config or default_config())
  File "/app/.heroku/python/lib/python3.6/site-packages/telegram_upload/config.py", line 15, in default_config
    json.dump({'api_id': api_id, 'api_hash': api_hash}, open(CONFIG_FILE, 'w'))
FileNotFoundError: [Errno 2] No such file or directory: '/app/.config/telegram-upload.json'

Please enlighten me.

**Comment by cyberboysumanjay** [comment]
I fixed this error by adding json file manually. 
In the next stage I got this: 
**Please enter your phone (or bot token)**
I want to know that if I enter Bot token here will the bot be able to upload files of size 1.5gb? As the Bot API doesn't allow file size of 1.5gb

**Comment by Nekmo** [comment]
No. You must enter a phone number.
